#!/bin/sh

if [ -f config.status ]; then
	make maintainer-clean
fi

./autogen.sh --enable-maintainer-mode \
		--enable-silent-rules \
		--disable-optimization \
		--enable-debug \
		--with-log-level=8 $*
