/*
 * dLeyna
 *
 * Copyright (C) 2013 Intel Corporation. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU Lesser General Public License,
 * version 2.1, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Ludovic Ferrandis <ludovic.ferrandis@intel.com>
 *
 */

#ifndef DLS_PROPS_DEF_H__
#define DLS_PROPS_DEF_H__

#include "props.h"

enum dls_props_index_t_ {
	DLS_PROP_INDEX_CHILD_COUNT,
	DLS_PROP_INDEX_PATH,
	DLS_PROP_INDEX_PARENT,
	DLS_PROP_INDEX_REFPATH,
	DLS_PROP_INDEX_RESTRICTED,
	DLS_PROP_INDEX_SEARCHABLE,
	DLS_PROP_INDEX_CREATOR,
	DLS_PROP_INDEX_DATE,
	DLS_PROP_INDEX_DISPLAY_NAME,
	DLS_PROP_INDEX_DLNA_MANAGED,
	DLS_PROP_INDEX_RES_RESOURCES,
	DLS_PROP_INDEX_URL,
	DLS_PROP_INDEX_URLS,
	DLS_PROP_INDEX_BITRATE,
	DLS_PROP_INDEX_BITS_PER_SAMPLE,
	DLS_PROP_INDEX_COLOR_DEPTH,
	DLS_PROP_INDEX_DURATION,
	DLS_PROP_INDEX_DLNA_PROFILE,
	DLS_PROP_INDEX_MIME_TYPE,
	DLS_PROP_INDEX_HEIGHT,
	DLS_PROP_INDEX_WIDTH,
	DLS_PROP_INDEX_SAMPLE_RATE,
	DLS_PROP_INDEX_SIZE,
	DLS_PROP_INDEX_UPDATE_COUNT,
	DLS_PROP_INDEX_ALBUM,
	DLS_PROP_INDEX_ALBUM_ART_URL,
	DLS_PROP_INDEX_ARTIST,
	DLS_PROP_INDEX_ARTISTS,
	DLS_PROP_INDEX_TYPE,
	DLS_PROP_INDEX_CONTAINER_UID,
	DLS_PROP_INDEX_CREATE_CLASSES,
	DLS_PROP_INDEX_GENRE,
	DLS_PROP_INDEX_OBJECT_UID,
	DLS_PROP_INDEX_TRACK_NUMBER,
	DLS_PROP_INDEX_TOTAL_DELETED_CC,
	DLS_PROP_INDEX_DLNA_CONVERSION,
	DLS_PROP_INDEX_DLNA_OPERATION,
	DLS_PROP_INDEX_DLNA_FLAGS,
	DLS_PROP_INDEX_LOCATION,
	DLS_PROP_INDEX_UDN,
	DLS_PROP_INDEX_DEVICE_TYPE,
	DLS_PROP_INDEX_FRIENDLY_NAME,
	DLS_PROP_INDEX_MANUFACTURER,
	DLS_PROP_INDEX_MANUFACTURER_URL,
	DLS_PROP_INDEX_MODEL_DESC,
	DLS_PROP_INDEX_MODEL_NAME,
	DLS_PROP_INDEX_MODEL_NUMBER,
	DLS_PROP_INDEX_MODEL_URL,
	DLS_PROP_INDEX_SERIAL_NUMBER,
	DLS_PROP_INDEX_PRESENTATION_URL,
	DLS_PROP_INDEX_ICON_URL,
	DLS_PROP_INDEX_SV_DLNA_CAPS,
	DLS_PROP_INDEX_SV_SEARCH_CAPS,
	DLS_PROP_INDEX_SV_SORT_CAPS,
	DLS_PROP_INDEX_SV_SORT_EXT_CAPS,
	DLS_PROP_INDEX_SV_FEATURE_LIST,
	DLS_PROP_INDEX_SV_SRT,
	DLS_PROP_INDEX_ESV_SYSTEM_UID,
	DLS_PROP_INDEX_MAX_COUNT
};

#define DLS_PROP_MASK_CHILD_COUNT	(1LL << DLS_PROP_INDEX_CHILD_COUNT)
#define DLS_PROP_MASK_PATH		(1LL << DLS_PROP_INDEX_PATH)
#define DLS_PROP_MASK_PARENT		(1LL << DLS_PROP_INDEX_PARENT)
#define DLS_PROP_MASK_REFPATH		(1LL << DLS_PROP_INDEX_REFPATH)
#define DLS_PROP_MASK_RESTRICTED	(1LL << DLS_PROP_INDEX_RESTRICTED)
#define DLS_PROP_MASK_SEARCHABLE	(1LL << DLS_PROP_INDEX_SEARCHABLE)
#define DLS_PROP_MASK_CREATOR		(1LL << DLS_PROP_INDEX_CREATOR)
#define DLS_PROP_MASK_DATE		(1LL << DLS_PROP_INDEX_DATE)
#define DLS_PROP_MASK_DISPLAY_NAME	(1LL << DLS_PROP_INDEX_DISPLAY_NAME)
#define DLS_PROP_MASK_DLNA_MANAGED	(1LL << DLS_PROP_INDEX_DLNA_MANAGED)
#define DLS_PROP_MASK_RES_RESOURCES	(1LL << DLS_PROP_INDEX_RES_RESOURCES)
#define DLS_PROP_MASK_URL		(1LL << DLS_PROP_INDEX_URL)
#define DLS_PROP_MASK_URLS		(1LL << DLS_PROP_INDEX_URLS)
#define DLS_PROP_MASK_BITRATE		(1LL << DLS_PROP_INDEX_BITRATE)
#define DLS_PROP_MASK_BITS_PER_SAMPLE	(1LL << DLS_PROP_INDEX_BITS_PER_SAMPLE)
#define DLS_PROP_MASK_COLOR_DEPTH	(1LL << DLS_PROP_INDEX_COLOR_DEPTH)
#define DLS_PROP_MASK_DURATION		(1LL << DLS_PROP_INDEX_DURATION)
#define DLS_PROP_MASK_DLNA_PROFILE	(1LL << DLS_PROP_INDEX_DLNA_PROFILE)
#define DLS_PROP_MASK_MIME_TYPE		(1LL << DLS_PROP_INDEX_MIME_TYPE)
#define DLS_PROP_MASK_HEIGHT		(1LL << DLS_PROP_INDEX_HEIGHT)
#define DLS_PROP_MASK_WIDTH		(1LL << DLS_PROP_INDEX_WIDTH)
#define DLS_PROP_MASK_SAMPLE_RATE	(1LL << DLS_PROP_INDEX_SAMPLE_RATE)
#define DLS_PROP_MASK_SIZE		(1LL << DLS_PROP_INDEX_SIZE)
#define DLS_PROP_MASK_UPDATE_COUNT	(1LL << DLS_PROP_INDEX_UPDATE_COUNT)
#define DLS_PROP_MASK_ALBUM		(1LL << DLS_PROP_INDEX_ALBUM)
#define DLS_PROP_MASK_ALBUM_ART_URL	(1LL << DLS_PROP_INDEX_ALBUM_ART_URL)
#define DLS_PROP_MASK_ARTIST		(1LL << DLS_PROP_INDEX_ARTIST)
#define DLS_PROP_MASK_ARTISTS		(1LL << DLS_PROP_INDEX_ARTISTS)
#define DLS_PROP_MASK_TYPE		(1LL << DLS_PROP_INDEX_TYPE)
#define DLS_PROP_MASK_CONTAINER_UID	(1LL << DLS_PROP_INDEX_CONTAINER_UID)
#define DLS_PROP_MASK_CREATE_CLASSES	(1LL << DLS_PROP_INDEX_CREATE_CLASSES)
#define DLS_PROP_MASK_GENRE		(1LL << DLS_PROP_INDEX_GENRE)
#define DLS_PROP_MASK_OBJECT_UID	(1LL << DLS_PROP_INDEX_OBJECT_UID)
#define DLS_PROP_MASK_TRACK_NUMBER	(1LL << DLS_PROP_INDEX_TRACK_NUMBER)
#define DLS_PROP_MASK_TOTAL_DELETED_CC	(1LL << DLS_PROP_INDEX_TOTAL_DELETED_CC)
#define DLS_PROP_MASK_DLNA_CONVERSION	(1LL << DLS_PROP_INDEX_DLNA_CONVERSION)
#define DLS_PROP_MASK_DLNA_OPERATION	(1LL << DLS_PROP_INDEX_DLNA_OPERATION)
#define DLS_PROP_MASK_DLNA_FLAGS	(1LL << DLS_PROP_INDEX_DLNA_FLAGS)
#define DLS_PROP_MASK_LOCATION		(1LL << DLS_PROP_INDEX_LOCATION)
#define DLS_PROP_MASK_UDN		(1LL << DLS_PROP_INDEX_UDN)
#define DLS_PROP_MASK_DEVICE_TYPE	(1LL << DLS_PROP_INDEX_DEVICE_TYPE)
#define DLS_PROP_MASK_FRIENDLY_NAME	(1LL << DLS_PROP_INDEX_FRIENDLY_NAME)
#define DLS_PROP_MASK_MANUFACTURER	(1LL << DLS_PROP_INDEX_MANUFACTURER)
#define DLS_PROP_MASK_MANUFACTURER_URL	(1LL << DLS_PROP_INDEX_MANUFACTURER_URL)
#define DLS_PROP_MASK_MODEL_DESC	(1LL << DLS_PROP_INDEX_MODEL_DESC)
#define DLS_PROP_MASK_MODEL_NAME	(1LL << DLS_PROP_INDEX_MODEL_NAME)
#define DLS_PROP_MASK_MODEL_NUMBER	(1LL << DLS_PROP_INDEX_MODEL_NUMBER)
#define DLS_PROP_MASK_MODEL_URL		(1LL << DLS_PROP_INDEX_MODEL_URL)
#define DLS_PROP_MASK_SERIAL_NUMBER	(1LL << DLS_PROP_INDEX_SERIAL_NUMBER)
#define DLS_PROP_MASK_PRESENTATION_URL	(1LL << DLS_PROP_INDEX_PRESENTATION_URL)
#define DLS_PROP_MASK_ICON_URL		(1LL << DLS_PROP_INDEX_ICON_URL)
#define DLS_PROP_MASK_SV_DLNA_CAPS	(1LL << DLS_PROP_INDEX_SV_DLNA_CAPS)
#define DLS_PROP_MASK_SV_SEARCH_CAPS	(1LL << DLS_PROP_INDEX_SV_SEARCH_CAPS)
#define DLS_PROP_MASK_SV_SORT_CAPS	(1LL << DLS_PROP_INDEX_SV_SORT_CAPS)
#define DLS_PROP_MASK_SV_SORT_EXT_CAPS	(1LL << DLS_PROP_INDEX_SV_SORT_EXT_CAPS)
#define DLS_PROP_MASK_SV_FEATURE_LIST	(1LL << DLS_PROP_INDEX_SV_FEATURE_LIST)
#define DLS_PROP_MASK_SV_SRT		(1LL << DLS_PROP_INDEX_SV_SRT)
#define DLS_PROP_MASK_ESV_SYSTEM_UID	(1LL << DLS_PROP_INDEX_ESV_SYSTEM_UID)

#define DLS_PROP_MASK_ALL_PROPS 	0xffffffffffffffff

#define DLS_PROP_MASK_ALL_DEVICE_PROPS (  \
	DLS_PROP_MASK_LOCATION		| \
	DLS_PROP_MASK_UDN		| \
	DLS_PROP_MASK_DEVICE_TYPE	| \
	DLS_PROP_MASK_FRIENDLY_NAME	| \
	DLS_PROP_MASK_MANUFACTURER	| \
	DLS_PROP_MASK_MANUFACTURER_URL	| \
	DLS_PROP_MASK_MODEL_DESC	| \
	DLS_PROP_MASK_MODEL_NAME	| \
	DLS_PROP_MASK_MODEL_NUMBER	| \
	DLS_PROP_MASK_MODEL_URL		| \
	DLS_PROP_MASK_SERIAL_NUMBER	| \
	DLS_PROP_MASK_PRESENTATION_URL	| \
	DLS_PROP_MASK_ICON_URL		| \
	DLS_PROP_MASK_SV_DLNA_CAPS	| \
	DLS_PROP_MASK_SV_SEARCH_CAPS	| \
	DLS_PROP_MASK_SV_SORT_CAPS	| \
	DLS_PROP_MASK_SV_SORT_EXT_CAPS	| \
	DLS_PROP_MASK_SV_FEATURE_LIST	| \
	DLS_PROP_MASK_SV_SRT		| \
	DLS_PROP_MASK_ESV_SYSTEM_UID)

#define DLS_PROP_MASK_COMMON_RES_PROPS (  \
	DLS_PROP_MASK_SIZE	 	| \
	DLS_PROP_MASK_UPDATE_COUNT	| \
	DLS_PROP_MASK_DLNA_PROFILE	| \
	DLS_PROP_MASK_DLNA_CONVERSION	| \
	DLS_PROP_MASK_DLNA_OPERATION	| \
	DLS_PROP_MASK_DLNA_FLAGS	| \
	DLS_PROP_MASK_MIME_TYPE)

#define DLS_PROP_MASK_COMMON_MS2_RES_PROPS (	  \
	DLS_PROP_MASK_COMMON_RES_PROPS		| \
	DLS_PROP_MASK_URLS)

#define DLS_PROP_MASK_COMMON_RES_RES_PROPS (	  \
	DLS_PROP_MASK_COMMON_RES_PROPS		| \
	DLS_PROP_MASK_URL)

#define DLS_PROP_MASK_ALL_COMMON_RES_PROPS (	  \
	DLS_PROP_MASK_BITRATE		 	| \
	DLS_PROP_MASK_SAMPLE_RATE		| \
	DLS_PROP_MASK_BITS_PER_SAMPLE	 	| \
	DLS_PROP_MASK_DURATION	 		| \
	DLS_PROP_MASK_WIDTH		 	| \
	DLS_PROP_MASK_HEIGHT	 		| \
	DLS_PROP_MASK_COLOR_DEPTH)

#define DLS_PROP_MASK_ALL_RES_RES_PROPS (	  \
	DLS_PROP_MASK_COMMON_RES_RES_PROPS	| \
	DLS_PROP_MASK_ALL_COMMON_RES_PROPS)

#define DLS_PROP_MASK_ALL_MS2_RES_PROPS (	  \
	DLS_PROP_MASK_COMMON_MS2_RES_PROPS	| \
	DLS_PROP_MASK_ALL_COMMON_RES_PROPS)

#define DLS_PROP_MASK_ALL_OBJECT_PROPS (  \
	DLS_PROP_MASK_DISPLAY_NAME	| \
	DLS_PROP_MASK_CREATOR		| \
	DLS_PROP_MASK_PATH		| \
	DLS_PROP_MASK_PARENT		| \
	DLS_PROP_MASK_TYPE		| \
	DLS_PROP_MASK_RESTRICTED	| \
	DLS_PROP_MASK_DLNA_MANAGED	| \
	DLS_PROP_MASK_OBJECT_UID)

#define DLS_PROP_MASK_ALL_ITEM_PROPS (	  \
	DLS_PROP_MASK_ALL_OBJECT_PROPS	| \
	DLS_PROP_MASK_ALL_MS2_RES_PROPS	| \
	DLS_PROP_MASK_ARTIST		| \
	DLS_PROP_MASK_ARTISTS		| \
	DLS_PROP_MASK_ALBUM		| \
	DLS_PROP_MASK_DATE		| \
	DLS_PROP_MASK_GENRE		| \
	DLS_PROP_MASK_TRACK_NUMBER	| \
	DLS_PROP_MASK_ALBUM_ART_URL	| \
	DLS_PROP_MASK_REFPATH		| \
	DLS_PROP_MASK_RES_RESOURCES)

#define DLS_PROP_MASK_ALL_CONTAINER_PROPS ( 	  \
	DLS_PROP_MASK_ALL_OBJECT_PROPS		| \
	DLS_PROP_MASK_COMMON_MS2_RES_PROPS	| \
	DLS_PROP_MASK_CHILD_COUNT		| \
	DLS_PROP_MASK_SEARCHABLE		| \
	DLS_PROP_MASK_CREATE_CLASSES		| \
	DLS_PROP_MASK_CONTAINER_UID		| \
	DLS_PROP_MASK_TOTAL_DELETED_CC		| \
	DLS_PROP_MASK_RES_RESOURCES)



dls_prop_map_t *dls_props_def_get(void);

#endif /* DLS_PROPS_DEF_H__ */
